/* tslint:disable */
/* eslint-disable */
/**
 * nx-poc API
 * My test API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateUser
 */
export interface CreateUser {
  /**
   *
   * @type {string}
   * @memberof CreateUser
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof CreateUser
   */
  name: string;
}
